### ISSUE TITLE
Implement flag.Func from 1.16

### ISSUE THREAD

**Issue by nvx** [jnovack/flag#2]
Go1.16 adds a new method Func() to the standard library flag package. https://tip.golang.org/pkg/flag/#Func

The release notes describes the new method as follows:
```
The new Func function allows registering a flag implemented by calling a function, as a lighter-weight alternative to implementing the Value interface.
```

This sounds super handy to me so would be great if this fork supports it too.

**Comment by jnovack** [comment]
implemented in 8a7c5ea
